#!/bin/bash
# This script uses gpioset to control GPIO pins.
# Assumes libgpiod-utils is installed and gpiochip0 corresponds to BCM pins.

function voice_esp32_reset()
{
	# Set GPIO24 to 1 (output high)
	gpioset gpiochip0 24=1
	# Set GPIO25 to 0 (output low)
	gpioset gpiochip0 25=0
	# Set GPIO25 to 1 (output high)
	gpioset gpiochip0 25=1
}

voice_esp32_reset
